build buster with old curl and focal with new curl for debugging tests

diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -18,26 +18,26 @@ jobs:
     strategy:
       matrix:
         include:
-          - os: buster
+          - os: buster # old curl
             compiler: g++
             cpp: 17
             asan: off
             ubsan: off
-          - os: focal
+          - os: focal # new curl
             compiler: clang++
             cpp: 17
             asan: off
             ubsan: on
-          - os: focal
-            compiler: g++-10
-            cpp: 20
-            asan: on
-            ubsan: off
-          - os: jammy
-            compiler: g++
-            cpp: 20
-            asan: on
-            ubsan: off
+          # - os: focal
+          #   compiler: g++-10
+          #   cpp: 20
+          #   asan: on
+          #   ubsan: off
+          # - os: jammy
+          #   compiler: g++
+          #   cpp: 20
+          #   asan: on
+          #   ubsan: off
 
     name: "${{matrix.os}}/${{matrix.compiler}}/c++${{matrix.cpp}}/asan=${{matrix.asan}}/ubsan=${{matrix.ubsan}}"
 
@@ -84,78 +84,78 @@ jobs:
       run: docker exec kphp-build-container-${{matrix.os}} bash -c 
               "make -C ${{env.kphp_build_dir}} -j$(nproc) test"
 
-    - name: Compile dummy PHP script
+    - name: Compile PHP script
       run: docker exec kphp-build-container-${{matrix.os}} bash -c 
-              "cd ${{env.kphp_build_dir}} && echo 'hello world' > demo.php && ${{env.kphp_root_dir}}/objs/bin/kphp2cpp --cxx ${{matrix.compiler}} demo.php && kphp_out/server -o --user kitten"
+              "chown -R kitten ${{env.kphp_root_dir}} && cd ${{env.kphp_root_dir}} && ${{env.kphp_root_dir}}/objs/bin/kphp2cpp --cxx ${{matrix.compiler}} test.php && kphp_out/server -o --user kitten"
 
-    - name: Polyfills composer install
-      run: docker exec kphp-build-container-${{matrix.os}} bash -c
-              "composer install -d ${{env.kphp_polyfills_dir}}"
+    # - name: Polyfills composer install
+    #   run: docker exec kphp-build-container-${{matrix.os}} bash -c
+    #           "composer install -d ${{env.kphp_polyfills_dir}}"
 
-    - name: Run python tests
-      id: python_tests
-      continue-on-error: true
-      run: docker exec kphp-build-container-${{matrix.os}} bash -c
-              "chown -R kitten /home && su kitten -c 'GITHUB_ACTIONS=1 KPHP_TESTS_POLYFILLS_REPO=${{env.kphp_polyfills_dir}} KPHP_CXX=${{matrix.compiler}} python3.7 -m pytest --tb=native -n$(nproc) ${{env.kphp_root_dir}}/tests/python/'"
+    # - name: Run python tests
+    #   id: python_tests
+    #   continue-on-error: true
+    #   run: docker exec kphp-build-container-${{matrix.os}} bash -c
+    #           "chown -R kitten /home && su kitten -c 'GITHUB_ACTIONS=1 KPHP_TESTS_POLYFILLS_REPO=${{env.kphp_polyfills_dir}} KPHP_CXX=${{matrix.compiler}} python3.7 -m pytest --tb=native -n$(nproc) ${{env.kphp_root_dir}}/tests/python/'"
 
-    - name: Prepare python tests artifacts
-      if: steps.python_tests.outcome == 'failure'
-      run: docker cp kphp-build-container-${{matrix.os}}:${{env.kphp_root_dir}}/tests/python/_tmp/ ${{runner.temp}} &&
-           rm -rf ${{runner.temp}}/_tmp/*/working_dir
+    # - name: Prepare python tests artifacts
+    #   if: steps.python_tests.outcome == 'failure'
+    #   run: docker cp kphp-build-container-${{matrix.os}}:${{env.kphp_root_dir}}/tests/python/_tmp/ ${{runner.temp}} &&
+    #        rm -rf ${{runner.temp}}/_tmp/*/working_dir
 
-    - name: Upload python tests artifacts
-      uses: actions/upload-artifact@v3
-      if: steps.python_tests.outcome == 'failure'
-      with:
-        path: ${{runner.temp}}/_tmp/
+    # - name: Upload python tests artifacts
+    #   uses: actions/upload-artifact@v3
+    #   if: steps.python_tests.outcome == 'failure'
+    #   with:
+    #     path: ${{runner.temp}}/_tmp/
 
-    - name: Fail pipeline if python tests failed
-      if: steps.python_tests.outcome == 'failure'
-      run: exit 1
+    # - name: Fail pipeline if python tests failed
+    #   if: steps.python_tests.outcome == 'failure'
+    #   run: exit 1
 
     - name: Remove docker container
       run: docker rm -f kphp-build-container-${{matrix.os}}
 
-  build-macos:
-    runs-on: ${{matrix.os}}-12
-    strategy:
-      matrix:
-        include:
-          - os: macos
-            compiler: clang++
-            cpp: 17
+  # build-macos:
+  #   runs-on: ${{matrix.os}}-12
+  #   strategy:
+  #     matrix:
+  #       include:
+  #         - os: macos
+  #           compiler: clang++
+  #           cpp: 17
 
-    name: "${{matrix.os}}/${{matrix.compiler}}/c++${{matrix.cpp}}"
+  #   name: "${{matrix.os}}/${{matrix.compiler}}/c++${{matrix.cpp}}"
     
-    steps:
-    - uses: actions/checkout@v3
+  #   steps:
+  #   - uses: actions/checkout@v3
 
-    # because of https://github.com/orgs/Homebrew/discussions/4612
-    - name: Check Environment
-      run: |
-        export HOMEBREW_NO_INSTALL_FROM_API=0
-        brew untap --force homebrew/cask
+  #   # because of https://github.com/orgs/Homebrew/discussions/4612
+  #   - name: Check Environment
+  #     run: |
+  #       export HOMEBREW_NO_INSTALL_FROM_API=0
+  #       brew untap --force homebrew/cask
 
-    - name: Setup Environment
-      run: |
-        brew tap shivammathur/php
-        brew update
-        brew install re2c cmake coreutils openssl libiconv re2 pcre yaml-cpp zstd googletest shivammathur/php/php@7.4 python@3.12
-        brew link --overwrite --force shivammathur/php/php@7.4
-        /usr/local/Frameworks/Python.framework/Versions/3.12/bin/python3.12 -m pip install --upgrade pip --break-system-packages && /usr/local/Frameworks/Python.framework/Versions/3.12/bin/pip3 install jsonschema install --break-system-packages jsonschema
+  #   - name: Setup Environment
+  #     run: |
+  #       brew tap shivammathur/php
+  #       brew update
+  #       brew install re2c cmake coreutils openssl libiconv re2 pcre yaml-cpp zstd googletest shivammathur/php/php@7.4 python@3.12
+  #       brew link --overwrite --force shivammathur/php/php@7.4
+  #       /usr/local/Frameworks/Python.framework/Versions/3.12/bin/python3.12 -m pip install --upgrade pip --break-system-packages && /usr/local/Frameworks/Python.framework/Versions/3.12/bin/pip3 install jsonschema install --break-system-packages jsonschema
 
-    - name: Run cmake
-      run: cmake -DCMAKE_CXX_COMPILER=${{matrix.compiler}} -DCMAKE_CXX_STANDARD=${{matrix.cpp}} -DDOWNLOAD_MISSING_LIBRARIES=On -S $GITHUB_WORKSPACE -B ${{runner.workspace}}/build
+  #   - name: Run cmake
+  #     run: cmake -DCMAKE_CXX_COMPILER=${{matrix.compiler}} -DCMAKE_CXX_STANDARD=${{matrix.cpp}} -DDOWNLOAD_MISSING_LIBRARIES=On -S $GITHUB_WORKSPACE -B ${{runner.workspace}}/build
 
-    - name: Build all
-      run: make -C ${{runner.workspace}}/build -j$(nproc) all
+  #   - name: Build all
+  #     run: make -C ${{runner.workspace}}/build -j$(nproc) all
       
-    - name: Run unit tests
-      run: make -C ${{runner.workspace}}/build -j$(nproc) test
+  #   - name: Run unit tests
+  #     run: make -C ${{runner.workspace}}/build -j$(nproc) test
 
-    - name: Compile dummy PHP script
-      working-directory: ${{runner.workspace}}/build
-      run: |
-        echo 'hello world' > demo.php 
-        $GITHUB_WORKSPACE/objs/bin/kphp2cpp --cxx ${{matrix.compiler}} demo.php
-        kphp_out/server -o
+  #   - name: Compile dummy PHP script
+  #     working-directory: ${{runner.workspace}}/build
+  #     run: |
+  #       echo 'hello world' > demo.php 
+  #       $GITHUB_WORKSPACE/objs/bin/kphp2cpp --cxx ${{matrix.compiler}} demo.php
+  #       kphp_out/server -o
