Add github action test

diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -11,6 +11,9 @@ env:
   kphp_root_dir: /home/kitten/kphp
   kphp_polyfills_dir: /home/kitten/kphp/kphp-polyfills
   kphp_build_dir: /home/kitten/kphp/build
+  session_php_script: /home/kitten/kphp/docs/session_test.php
+  kphp_snippets_dir: /home/kitten/kphp/kphp-snippets
+  kphp_snippets_jobs_dir: /home/kitten/kphp/kphp-snippets/JobWorkers
 
 jobs:
   build-linux:
@@ -18,11 +21,11 @@ jobs:
     strategy:
       matrix:
         include:
-          - os: buster
-            compiler: g++
-            cpp: 17
-            asan: off
-            ubsan: off
+          # - os: buster
+          #   compiler: g++
+          #   cpp: 17
+          #   asan: off
+          #   ubsan: off
           - os: focal
             compiler: clang++
             cpp: 17
@@ -49,6 +52,12 @@ jobs:
       with:
         repository: 'VKCOM/kphp-polyfills'
         path: 'kphp-polyfills'
+
+    - name: Get snippets repo
+      uses: actions/checkout@v3
+      with:
+        repository: 'VKCOM/kphp-snippets'
+        path: 'kphp-snippets'
 
     - name: Cache docker image
       uses: actions/cache@v3
@@ -80,82 +89,99 @@ jobs:
       run: docker exec kphp-build-container-${{matrix.os}} bash -c 
               "cmake -DCMAKE_CXX_COMPILER=${{matrix.compiler}} -DCMAKE_CXX_STANDARD=${{matrix.cpp}} -DADDRESS_SANITIZER=${{matrix.asan}} -DUNDEFINED_SANITIZER=${{matrix.ubsan}} -DPDO_DRIVER_MYSQL=ON -DPDO_DRIVER_PGSQL=ON -DPDO_LIBS_STATIC_LINKING=ON -S ${{env.kphp_root_dir}} -B ${{env.kphp_build_dir}} && make -C ${{env.kphp_build_dir}} -j$(nproc) all"
 
-    - name: Run unit tests
-      run: docker exec kphp-build-container-${{matrix.os}} bash -c 
-              "make -C ${{env.kphp_build_dir}} -j$(nproc) test"
+    # - name: Run unit tests
+    #   run: docker exec kphp-build-container-${{matrix.os}} bash -c 
+    #           "make -C ${{env.kphp_build_dir}} -j$(nproc) test"
 
-    - name: Compile dummy PHP script
-      run: docker exec kphp-build-container-${{matrix.os}} bash -c 
-              "cd ${{env.kphp_build_dir}} && echo 'hello world' > demo.php && ${{env.kphp_root_dir}}/objs/bin/kphp2cpp --cxx ${{matrix.compiler}} demo.php && kphp_out/server -o --user kitten"
+    # - name: Compile dummy PHP script
+    #   run: docker exec kphp-build-container-${{matrix.os}} bash -c 
+    #           "cd ${{env.kphp_build_dir}} && echo 'hello world' > demo.php && ${{env.kphp_root_dir}}/objs/bin/kphp2cpp --cxx ${{matrix.compiler}} demo.php && kphp_out/server -o --user kitten"
 
-    - name: Polyfills composer install
+    # - name: Polyfills composer install
+    #   run: docker exec kphp-build-container-${{matrix.os}} bash -c
+    #           "composer install -d ${{env.kphp_polyfills_dir}}"
+
+    # - name: Run python tests
+    #   id: python_tests
+    #   continue-on-error: true
+    #   run: docker exec kphp-build-container-${{matrix.os}} bash -c
+    #           "chown -R kitten /home && su kitten -c 'GITHUB_ACTIONS=1 KPHP_TESTS_POLYFILLS_REPO=${{env.kphp_polyfills_dir}} KPHP_CXX=${{matrix.compiler}} python3.7 -m pytest --tb=native -n$(nproc) ${{env.kphp_root_dir}}/tests/python/'"
+
+    # - name: Prepare python tests artifacts
+    #   if: steps.python_tests.outcome == 'failure'
+    #   run: docker cp kphp-build-container-${{matrix.os}}:${{env.kphp_root_dir}}/tests/python/_tmp/ ${{runner.temp}} &&
+    #        rm -rf ${{runner.temp}}/_tmp/*/working_dir
+
+    # - name: Upload python tests artifacts
+    #   uses: actions/upload-artifact@v3
+    #   if: steps.python_tests.outcome == 'failure'
+    #   with:
+    #     path: ${{runner.temp}}/_tmp/
+
+    # - name: Fail pipeline if python tests failed
+    #   if: steps.python_tests.outcome == 'failure'
+    #   run: exit 1
+
+    - name: Copy the session_test file
       run: docker exec kphp-build-container-${{matrix.os}} bash -c
-              "composer install -d ${{env.kphp_polyfills_dir}}"
+              "su kitten -c 'cp ${{env.session_php_script}} ${{env.kphp_snippets_dir}}/JobWorkers/'"
 
-    - name: Run python tests
-      id: python_tests
-      continue-on-error: true
+    - name: Compile the session_test project
       run: docker exec kphp-build-container-${{matrix.os}} bash -c
-              "chown -R kitten /home && su kitten -c 'GITHUB_ACTIONS=1 KPHP_TESTS_POLYFILLS_REPO=${{env.kphp_polyfills_dir}} KPHP_CXX=${{matrix.compiler}} python3.7 -m pytest --tb=native -n$(nproc) ${{env.kphp_root_dir}}/tests/python/'"
+              "su kitten -c 'cd ${{env.kphp_snippets_dir}}/JobWorkers/ && ${{env.kphp_root_dir}}/objs/bin/kphp2cpp --cxx ${{matrix.compiler}} session_test.php -I .. -M server'"
 
-    - name: Prepare python tests artifacts
-      if: steps.python_tests.outcome == 'failure'
-      run: docker cp kphp-build-container-${{matrix.os}}:${{env.kphp_root_dir}}/tests/python/_tmp/ ${{runner.temp}} &&
-           rm -rf ${{runner.temp}}/_tmp/*/working_dir
+    - name: Start the server
+      run: docker exec kphp-build-container-${{matrix.os}} bash -c
+              "su kitten -c 'cd ${{env.kphp_snippets_dir}}/JobWorkers/ && ./kphp_out/server -f 2 --http-port 8080 --job-workers-ratio 0.5 --sql-port 5555 &> log.txt &'"
 
-    - name: Upload python tests artifacts
-      uses: actions/upload-artifact@v3
-      if: steps.python_tests.outcome == 'failure'
-      with:
-        path: ${{runner.temp}}/_tmp/
+    - name: Send a request to the server
+      run: docker exec kphp-build-container-${{matrix.os}} bash -c
+              "curl 'http://localhost:8080'"
 
-    - name: Fail pipeline if python tests failed
-      if: steps.python_tests.outcome == 'failure'
-      run: exit 1
+    # - name: Remove docker container
+    #   run: docker rm -f kphp-build-container-${{matrix.os}}
 
-    - name: Remove docker container
-      run: docker rm -f kphp-build-container-${{matrix.os}}
 
-  build-macos:
-    runs-on: ${{matrix.os}}-12
-    strategy:
-      matrix:
-        include:
-          - os: macos
-            compiler: clang++
-            cpp: 17
+  # build-macos:
+  #   runs-on: ${{matrix.os}}-12
+  #   strategy:
+  #     matrix:
+  #       include:
+  #         - os: macos
+  #           compiler: clang++
+  #           cpp: 17
 
-    name: "${{matrix.os}}/${{matrix.compiler}}/c++${{matrix.cpp}}"
+  #   name: "${{matrix.os}}/${{matrix.compiler}}/c++${{matrix.cpp}}"
     
-    steps:
-    - uses: actions/checkout@v3
+  #   steps:
+  #   - uses: actions/checkout@v3
 
-    # because of https://github.com/orgs/Homebrew/discussions/4612
-    - name: Check Environment
-      run: |
-        export HOMEBREW_NO_INSTALL_FROM_API=0
-        brew untap --force homebrew/cask
+  #   # because of https://github.com/orgs/Homebrew/discussions/4612
+  #   - name: Check Environment
+  #     run: |
+  #       export HOMEBREW_NO_INSTALL_FROM_API=0
+  #       brew untap --force homebrew/cask
 
-    - name: Setup Environment
-      run: |
-        brew tap shivammathur/php
-        brew update
-        brew install re2c cmake coreutils openssl libiconv re2 pcre yaml-cpp zstd googletest shivammathur/php/php@7.4
-        brew link --overwrite --force shivammathur/php/php@7.4
-        /usr/local/Frameworks/Python.framework/Versions/3.12/bin/python3.12 -m pip install --upgrade pip --break-system-packages && /usr/local/Frameworks/Python.framework/Versions/3.12/bin/pip3 install jsonschema install --break-system-packages jsonschema
+  #   - name: Setup Environment
+  #     run: |
+  #       brew tap shivammathur/php
+  #       brew update
+  #       brew install re2c cmake coreutils openssl libiconv re2 pcre yaml-cpp zstd googletest shivammathur/php/php@7.4
+  #       brew link --overwrite --force shivammathur/php/php@7.4
+  #       /usr/local/Frameworks/Python.framework/Versions/3.12/bin/python3.12 -m pip install --upgrade pip --break-system-packages && /usr/local/Frameworks/Python.framework/Versions/3.12/bin/pip3 install jsonschema install --break-system-packages jsonschema
 
-    - name: Run cmake
-      run: cmake -DCMAKE_CXX_COMPILER=${{matrix.compiler}} -DCMAKE_CXX_STANDARD=${{matrix.cpp}} -DDOWNLOAD_MISSING_LIBRARIES=On -S $GITHUB_WORKSPACE -B ${{runner.workspace}}/build
+  #   - name: Run cmake
+  #     run: cmake -DCMAKE_CXX_COMPILER=${{matrix.compiler}} -DCMAKE_CXX_STANDARD=${{matrix.cpp}} -DDOWNLOAD_MISSING_LIBRARIES=On -S $GITHUB_WORKSPACE -B ${{runner.workspace}}/build
 
-    - name: Build all
-      run: make -C ${{runner.workspace}}/build -j$(nproc) all
+  #   - name: Build all
+  #     run: make -C ${{runner.workspace}}/build -j$(nproc) all
       
-    - name: Run unit tests
-      run: make -C ${{runner.workspace}}/build -j$(nproc) test
+  #   - name: Run unit tests
+  #     run: make -C ${{runner.workspace}}/build -j$(nproc) test
 
-    - name: Compile dummy PHP script
-      working-directory: ${{runner.workspace}}/build
-      run: |
-        echo 'hello world' > demo.php 
-        $GITHUB_WORKSPACE/objs/bin/kphp2cpp --cxx ${{matrix.compiler}} demo.php
-        kphp_out/server -o
+  #   - name: Compile dummy PHP script
+  #     working-directory: ${{runner.workspace}}/build
+  #     run: |
+  #       echo 'hello world' > demo.php 
+  #       $GITHUB_WORKSPACE/objs/bin/kphp2cpp --cxx ${{matrix.compiler}} demo.php
+  #       kphp_out/server -o
